version: "3.8"
services: 
    lorawan-pipeline:
       build:
         context: .
         dockerfile: Debug.Dockerfile
       ports:
        - 30000:30000   
       networks:
        - lora
       container_name: lorawan-pipeline
       environment:
        - ASPNETCORE_ENVIRONMENT=Test

networks:
  lora:
    name: lora

volumes:
  devices_mongo: