version: "3.8"
services: 
    storage-container:
       build:
         context: .
         dockerfile: Debug.Dockerfile
       ports:
        - 30002:30002   
       networks:
        - lora
       container_name: storage-container
       environment:
        - ASPNETCORE_ENVIRONMENT=Test
       volumes:
        - storage_mongo:/data/db 

networks:
  lora:
    name: lora

volumes:
  storage_mongo: